### ISSUE TITLE
맵 렌더시 앱이 강제 종료되어 버립니다.

### ISSUE THREAD

**Issue by skout90** [asata/react-native-daummap#5]
react-native 0.56.0 환경, 안드로이드에서 작업하였고.
맵 렌더시에, GPS권한을 묻고, 허용을 하면 바로 앱이 강제종료 되어 버립니다.
혹시 짐작가는 문제가 있으신가요?

(디버그 메세지도 아무것도 찍히지 않아서, 어떤 정보를 드려야 할지 모르겠네요;)

**Comment by asata** [comment]
adb logcat 에서 표시되는 메시지를 확인 해 볼 수 있을까요?

**Comment by skout90** [comment]
@asata 넵 아래와 같습니다.
````
10-19 01:23:43.112   308   308 I GnssLocationProvider: WakeLock acquired by sendMessage(SET_REQUEST, 0, com.android.server.location.GnssLocationProvider$GpsRequest@ee53d39)
10-19 01:23:43.113   308   322 I GnssLocationProvider: WakeLock released by handleMessage(SET_REQUEST, 0, com.android.server.location.GnssLocationProvider$GpsRequest@ee53d39)
10-19 01:23:43.163   308   322 E memtrack: Couldn't load memtrack module
10-19 01:23:43.163   308   322 W android.os.Debug: failed to get memory consumption info: -1
10-19 01:23:43.164   346   346 D Sensors : batch handle 1, but there is no batch sensor in genymotion
10-19 01:23:43.202   308   322 E memtrack: Couldn't load memtrack module
10-19 01:23:43.202   308   322 W android.os.Debug: failed to get memory consumption info: -1
10-19 01:23:43.227  4643  4643 E net.daum.mf.map.n.api.NativeMapLibraryLoader: Can`t load DaumMapEngineApi.so file
10-19 01:23:43.228  4643  4643 D AndroidRuntime: Shutting down VM
10-19 01:23:43.229  4643  4643 E AndroidRuntime: FATAL EXCEPTION: main
10-19 01:23:43.229  4643  4643 E AndroidRuntime: Process: com.example, PID: 4643
10-19 01:23:43.229  4643  4643 E AndroidRuntime: java.lang.UnsatisfiedLinkError
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at net.daum.mf.map.n.api.NativeMapLibraryLoader.loadLibrary(NativeMapLibraryLoader.java:39)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at net.daum.mf.map.n.api.NativeThread.<clinit>(NativeThread.java:6)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at android.opengl.alt.GLSurfaceView.setRenderer(GLSurfaceView.java:302)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at net.daum.android.map.MapView.init(MapView.java:43)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at net.daum.android.map.MapView.<init>(MapView.java:55)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at net.daum.mf.map.api.MapView.<init>(MapView.java:460)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at com.teamsf.daummap.RNMapView.<init>(RNMapView.java:20)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at com.teamsf.daummap.DaumMapManager.createViewInstance(DaumMapManager.java:48)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at com.teamsf.daummap.DaumMapManager.createViewInstance(DaumMapManager.java:27)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:42)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:260)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:888)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1001)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at com.facebook.react.uimanager.UIViewOperationQueue.access$2400(UIViewOperationQueue.java:46)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1061)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at android.view.Choreographer.doCallbacks(Choreographer.java:723)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at android.view.C


horeographer.doFrame(Choreographer.java:655)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at android.os.Handler.handleCallback(Handler.java:789)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at android.os.Handler.dispatchMessage(Handler.java:98)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:164)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at android.app.ActivityThread.main(ActivityThread.java:6541)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at java.lang.reflect.Method.invoke(Native Method)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-19 01:23:43.229  4643  4643 E AndroidRuntime:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-19 01:23:43.232   308   760 W ActivityManager:   Force finishing activity com.example/.MainActivity
10-19 01:23:43.234   308   324 I ActivityManager: Showing crash dialog for package com.example u0
10-19 01:23:43.282   308  1199 I OpenGLRenderer: Initialized EGL, version 1.4
10-19 01:23:43.282   308  1199 D OpenGLRenderer: Swap behavior 1
10-19 01:23:43.285   308  1199 D EGL_emulation: eglCreateContext: 0xe52bece0: maj 2 min 0 rcv 2
10-19 01:23:43.429   345   345 E hw-IPCThreadState: binder thread pool (1 threads) starved for 140 ms
10-19 01:23:43.461   308   324 W Looper  : Dispatch took 200ms on android.ui, h=Handler (android.view.Choreographer$FrameHandler) {dca003} cb=android.view.Choreographer$FrameDisplayEventReceiver@c033b80 msg=0
10-19 01:23:43.498   308  1199 E EGL_emulation: tid 1199: eglSurfaceAttrib(1210): error 0x3009 (EGL_BAD_MATCH)
10-19 01:23:43.498   308  1199 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xc301a300, error=EGL_BAD_MATCH
10-19 01:23:43.642   308   324 W Looper  : Dispatch took 180ms on android.ui, h=Handler (android.view.Choreographer$FrameHandler) {dca003} cb=android.view.Choreographer$FrameDisplayEventReceiver@c033b80 msg=0
10-19 01:23:43.732   308   323 W ActivityManager: Activity pause timeout for ActivityRecord{8214b1 u0 com.example/.MainActivity t118 f}
10-19 01:23:43.748  2883  2883 I ackageinstaller: type=1400 audit(0.0:2879): avc: denied { sendto } for path="/dev/socket/logdw" scontext=u:r:platform_app:s0:c512,c768 tcontext=u:r:init:s0 tclass=unix_dgram_socket permissive=1
10-19 01:23:43.778   354   354 W SurfaceFlinger: couldn't log to binary event log: overflow.
10-19 01:23:43.908  1141  1228 E EGL_emulation: tid 1228: eglSurfaceAttrib(1210): error 0x3009 (EGL_BAD_MATCH)
10-19 01:23:43.908  1141  1228 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xc83fb080, error=EGL_BAD_MATCH
10-19 01:23:44.073   354   354 E EGL_emulation: tid 354: eglCreateSyncKHR(1881): error 0x3004 (EGL_BAD_ATTRIBUTE)
10-19 01:23:44.380  1141  1228 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
10-19 01:23:44.380  1141  1228 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
10-19 01:23:44.955   308   322 E memtrack: Couldn't load memtrack module
10-19 01:23:44.955   308   322 W android.os.Debug: failed to get memory consumption info: -1
10-19 01:23:46.061  1736  1736 I Finsky  : [2] com.google.android.finsky.scheduler.JobSchedulerEngine$PhoneskyJobSchedulerJobService.onStartJob(7): onJobSchedulerWakeup with jobId 9001
10-19 01:23:46.063  1736  1736 I Finsky  : [2] com.google.android.finsky.scheduler.ae.a(29): Scheduling fallback job with id: 9034, and delay: 43200000 ms
10-19 01:23:46.064  1736  1736 I Finsky  : [2] com.google.android.finsky.scheduler.ae.a(39): Scheduling fallback in 64799999 (absolute: 67610603)
10-19 01:23:46.068  1736  1736 I Finsky  : [2] com.google.android.finsky.scheduler.am.handleMessage(16): DeviceState: DeviceState{currentTime=1539912226067, isCharging=true, isIdle=false, netAny=true, netNotRoaming=true, netUnmetered=true}

0-19 01:23:46.069  1736  1736 I Finsky  : [2] com.google.android.finsky.scheduler.bp.a(66): Jobs in database: 1-1337 12-1 26-1414141414 
10-19 01:23:46.071  1736  1736 I Finsky  : [2] com.google.android.finsky.scheduler.ah.a(59): Running job: 12-1
10-19 01:23:46.076  1736  1736 I Finsky  : [2] com.google.android.finsky.contentsync.ContentSyncJob.a(30): ContentSyncJob started
10-19 01:23:46.077  1736  1736 I Finsky  : [2] com.google.android.finsky.scheduler.ah.a(105): RunningQueue size: 1, PendingQueue size: 0
10-19 01:23:46.077  1736  1736 I Finsky  : [2] com.google.android.finsky.scheduler.ah.a(116): Running queue: 12-1 
10-19 01:23:46.079  1736  1773 I Finsky  : [159] com.google.android.finsky.n.c.a(20): Completed 0 account content syncs with 0 successful.
10-19 01:23:46.080  1736  1736 I Finsky  : [2] com.google.android.finsky.contentsync.ContentSyncJob.a(28): Installation state replication succeeded.
10-19 01:23:46.080  1736  1736 I Finsky  : [2] com.google.android.finsky.scheduler.bm.b(8): jobFinished: 12-1. TimeElapsed: 3ms
10-19 01:23:46.080  1736  1736 I Finsky  : [2] com.google.android.finsky.scheduler.ah.a(138): Job 12-1 finished
10-19 01:23:46.081  1736  1736 I Finsky  : [2] com.google.android.finsky.scheduler.ah.a(105): RunningQueue size: 0, PendingQueue size: 0
10-19 01:23:46.081  1736  1736 I Finsky  : [2] com.google.android.finsky.scheduler.am.handleMessage(42): Executor finished
10-19 01:23:46.088  1736  1736 I Finsky  : [2] com.google.android.finsky.scheduler.bp.a(66): Jobs in database: 1-1337 26-1414141414 
10-19 01:23:46.089  1736  1736 I Finsky  : [2] com.google.android.finsky.scheduler.l.a(70): ConstraintMapping: 1-1337,  -> L: 12561579ms, D: 98961579ms, C: false, I: false, N: 1
10-19 01:23:46.089  1736  1736 I Finsky  : [2] com.google.android.finsky.scheduler.l.a(70): ConstraintMapping: 26-1414141414,  -> L: 40414946ms, D: 41314946ms, C: false, I: false, N: 0
10-19 01:23:46.089  1736  1736 I Finsky  : [2] com.google.android.finsky.scheduler.JobSchedulerEngine.a(108): Cancelling existing job with id: 9002
10-19 01:23:46.090  1736  1736 I Finsky  : [2] com.google.android.finsky.scheduler.JobSchedulerEngine.a(47): Scheduling job Id: 9000, L: 12561579, D: 98961579, C: false, I: false, N: 1
10-19 01:23:46.091  1736  1736 I Finsky  : [2] com.google.android.finsky.scheduler.JobSchedulerEngine.a(47): Scheduling job Id: 9003, L: 40414946, D: 41314946, C: false, I: false, N: 0
10-19 01:23:47.991   308   760 W ActivityManager:   Force finishing activity com.example/.MainActivity
10-19 01:23:47.996   308   760 I ActivityManager: Killing 4643:com.example/u0a135 (adj 900): crash
10-19 01:23:48.027   346   346 D Sensors : batch handle 1, but there is no batch sensor in genymotion
10-19 01:23:48.219   308   324 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
10-19 01:23:48.219   308   324 W ViewRootImpl[example]: Dropping event due to root view being removed: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=682.50037, y[0]=-198.3266, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=2812592, downTime=2812530, deviceId=1, source=0x1002 }
10-19 01:23:48.223   308   330 W ActivityManager: setHasOverlayUi called on unknown pid: 4643
10-19 01:23:48.413   308   484 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
````

**Comment by skout90** [comment]
@asata 
Genymotion 2.12.2 - 안드로이드(API26) 환경에서 개발을 하고 있는데요.
지니모션이 아닌 실제 디바이스에서 apk를 다운받아 실행을 시키니까 문제 없이 되네요.

지니모션에서는 사용이 어려울까요? 개발을 안드로이드 에뮬레이터를 통해 하시나요?

> 안드로이드 에뮬레이터(API28)에서도 안되는것 확인했습니다.

**Comment by asata** [comment]
해당하는 오류는 에뮬레이터에서 지도에 필요한 라이브러리 파일을 읽어들이지 못해 발생하는 오류입니다.
필요한 라이브러리 파일인 DaumMapEngineApi.so는 arm 및 armv7 기기만 지원하고 있습니다.
에뮬레이터에서 실행할 경우 해당 파일을 읽지 못해 앱이 실행되지 않습니다.

https://devtalk.kakao.com/t/android-studio-kakaomap-canot-load-so-file/36114

**Comment by venzersiz** [comment]
@asata 이거 때문에 한참 고생했네요. 관련 내용 README에 반영해주시면 좋을 것 같습니다.

**Comment by mynameyj** [comment]
@asata 에뮬레이터도 그렇고 디바이스(노트7FE)도 그렇고 다 안되네요 ㅠ
증상은 똑같습니다. 위치허용하고 난뒤 강종이네요. 아...

**Comment by mynameyj** [comment]
@venzersiz 혹시 해결하셨나요...? 전 여전히 맵만 로드하면 앱이 강종되네요... 디바이스로 해도 그렇습니다 ㅠ

**Comment by venzersiz** [comment]
@mynameyj 지도 줌 레벨이 변경 안되는 거 같이 이 라이브러리를 현재 사용하지 않습니다. 애초에 리액트 네이티브를 하지 않고 있어요. 제대로 된 게 나오기 전까지 그냥 구글 맵을 쓰시는 것이 정신 건강에 좋을 것 같어요. 아니면 직접 만드시던지요. 저는 실력이 아직 부족하여 안드로이드 네이티브부터 공부 중입니다.
